/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as RecipeIdRouteImport } from './routes/$recipeId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipeIdEditRouteImport } from './routes/$recipeId_.edit'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeIdRoute = RecipeIdRouteImport.update({
  id: '/$recipeId',
  path: '/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeIdEditRoute = RecipeIdEditRouteImport.update({
  id: '/$recipeId_/edit',
  path: '/$recipeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$recipeId': typeof RecipeIdRoute
  '/new': typeof NewRoute
  '/$recipeId/edit': typeof RecipeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$recipeId': typeof RecipeIdRoute
  '/new': typeof NewRoute
  '/$recipeId/edit': typeof RecipeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$recipeId': typeof RecipeIdRoute
  '/new': typeof NewRoute
  '/$recipeId_/edit': typeof RecipeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$recipeId' | '/new' | '/$recipeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$recipeId' | '/new' | '/$recipeId/edit'
  id: '__root__' | '/' | '/$recipeId' | '/new' | '/$recipeId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipeIdRoute: typeof RecipeIdRoute
  NewRoute: typeof NewRoute
  RecipeIdEditRoute: typeof RecipeIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$recipeId': {
      id: '/$recipeId'
      path: '/$recipeId'
      fullPath: '/$recipeId'
      preLoaderRoute: typeof RecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$recipeId_/edit': {
      id: '/$recipeId_/edit'
      path: '/$recipeId/edit'
      fullPath: '/$recipeId/edit'
      preLoaderRoute: typeof RecipeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipeIdRoute: RecipeIdRoute,
  NewRoute: NewRoute,
  RecipeIdEditRoute: RecipeIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
